### ISSUE TITLE
Add relabeling option in the ServiceMonitor object

### ISSUE THREAD

**Issue by amartingarcia** [devopstales/trivy-operator#24]
Hello,
I would like to add the relabeling section to the service monitor, the object would look like this:

```yaml
{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    serviceapp: {{ include "trivy-operator.fullname" . }}-trivy-operator
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ include "trivy-operator.fullname" . }}-trivy-operator
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - interval: 60s
    path: /
    scrapeTimeout: 30s
    targetPort: 9115
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 4 }}
{{- end }}

  selector:
    matchLabels:
      app: trivy-operator
      service: metrics
{{- end }}
```

And values file:
```yaml
serviceMonitor:
  enabled: true
  labels:
    release: prometheus
  relabelings: []
```

Thanks! :)
