### ISSUE TITLE
Ability to add a certain label to the Metrics

### ISSUE THREAD

**Issue by sherifkayad** [devopstales/trivy-operator#37]
Currently the official Trivy Operator provides a very strong and much needed feature that's enabling Kubernetes labels (on the Workloads to scan) as metrics labels.

Would be great to also have such feature.

Reference: https://aquasecurity.github.io/trivy-operator/v0.7.1/integrations/metrics/#adding-custom-label-to-metrics

**Comment by devopstales** [comment]
Hi @sherifkayad,

Thank you for your interest  in the original Trivy Operator. I didn't see why it is a  "very strong and much needed feature". I read the linked documentation but it didn't clean to me what will be the value of this custom label.  Perhaps if you if you tell me more what purpose do you want to achieve it would be easier to me.

**Comment by sherifkayad** [comment]
@devopstales one use case we have is to be able to filter in Grafana / alert the responsible team for a certain service dynamically by reading a `team` & `app` labels from the k8s objects.

In our current PoC with the original operator that's possible to add those two labels to the metrics generated and hence being able to do exactly that.

I hope I managed to answer your question.

**Comment by sherifkayad** [comment]
@devopstales I might think there's a slight misunderstanding from your side. Assuming you have a `Deployment` object e.g. with the name `service-x-deployment` that looks like that:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-x-deployment
  namespace: whatever
  labels:
    app: service-x
    owner: team-a
    ping: pong
    otherLabel: otherValue
...
spec:
...
    spec:
      containers:
        - name: service-x
          image: >-
            my-registry/service-x:myTag
...
```
 
Specifying the Trivy Operator `trivyOperator.reportResourceLabels": "owner,app"` will lead that all vulnerability reports generated out of this deployment object (e.g. the Image Vulnerability Reports towards `my-registry/mycontainer:myTag`) will have the metric label `owner` set to `team-a` and `app` set to `service-x`. The same applies to the rest of the scans performed on the other k8s objects and generating other reports in the Trivy Operator CRD ..

E.g. you might end up with something like:
```yaml
apiVersion: aquasecurity.github.io/v1alpha1
kind: VulnerabilityReport
metadata:
  labels:
    owner: team-a
    app: service-x
    resource-spec-hash: 7b7979f777
    trivy-operator.container.name: service-x
    trivy-operator.resource.kind: ReplicaSet
    trivy-operator.resource.name: service-x-65c76595f
    trivy-operator.resource.namespace: whatever
  name: replicaset-service-x-65c76595f-service-x
  namespace: whatever
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: false
      controller: true
      kind: ReplicaSet
      name: service-x-65c76595f
      uid: 79387df7-e1a3-4a2b-8615-37b05aa14a9d
report:
  artifact:
    repository: my-registry/service-x
    tag: myTag
  registry:
    server: my-registry
  scanner:
    name: Trivy
    vendor: Aqua Security
    version: 0.34.0
  summary:
    criticalCount: 2
    highCount: 30
    lowCount: 314
    mediumCount: 23
    noneCount: 0
    unknownCount: 0
  updateTimestamp: '2022-11-28T12:48:27Z'
  vulnerabilities:
    ...
...
```

And then of course on the metrics side of things, you would be able to query something like:
```
trivy_clusterrole_clusterrbacassessments{app="service-x", owner="team-a"}
trivy_image_exposedsecrets{app="service-x", owner="team-a"}
trivy_image_vulnerabilities{app="service-x", owner="team-a"}
trivy_resource_configaudits{app="service-x", owner="team-a"}
```
